apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for the internal application
namespace: llm-gateway-internal


# Resources from base (if any)
resources:
  - ../../base
  - secrets-manager-password.yaml
  - secret-store.yaml
  - external-secrets.yaml

patches:
  - path: migrations-job-sync-wave.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: litellm-migrations
  - path: deployment-sync-wave.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: litellm
