apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for the internal application
namespace: llm-gateway-internal


# Resources from base (if any)
resources:
  - ../../base
  - secret-store.yaml
  - external-secrets.yaml
