"apiVersion": "external-secrets.io/v1"
"kind": "SecretStore"
"metadata":
  "name": "secret-store"
  "namespace": "llm-gateway-internal"
  "annotations":
    "argocd.argoproj.io/sync-wave": "-2"
"spec":
  "provider":
    "vault":
      "auth":
        "userPass":
          "path": "userpass"
          "secretRef":
            "key": "password"
            "name": "secrets-manager-password"
          "username": "sm51meey0q949g8h"
      "path": "1255167d-f5a4-4cc9-8419-f8aa17da98cf"
      "server": "https://prod.sm.eu01.stackit.cloud"
      "version": "v2"
