---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secrets-manager-password
  namespace: llm-gateway-internal
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    password: AgAf7H8AD9YyjzZz68DzC5JeeH4bbI6cK1BFTHHmHIAX78wNZrllDrtqeX7+gjxOtD/Tu8+cCGI1vyWNiBajGEBXWrMgrlEtzneNvH9X8PLcqYDCQlGBEqLhZBuQ8BjuszsUrS8ojg4efsNsf/wyot2/5TRchX64ZvXgrcsgXsjCPqOEz1yCjjdMorYQCfFbo7sV3uoVR7zCkubhVuYynhBYvhtZmTgmq5fPyKQCSXKY7SgWtF6uo/ny95dkSp3JXyKvpjDAp04zNSjLbaHq+bajVW8UzE/z/YuiBzzy7C8i40abCZMPF8azNE/mejznJxjOTxjCMxXGxhZ3/uLVUhIeeQ6+3fCtDCmgASCdeK5Z30Zxo4ikxMkDzKt13bYu/33FFf+X126yS8mE5PkY7Ogok0gfdCf45rlg/Ueq4oKJ1kD7b10rpQNhSF+9SUW5ggN1lpC9a2dgj6zVRBrSIhKA6Z/TMuMmI2LCWd7eIh2cnPNwLkM+Z8ryqbOldVk6jGxTojrTTp1jJW+eE56PmDmdk/F3H1JVc0nQ8bGEelGJUx4jBuaRur6/RDTNqjkypeOkOdOJj+x9qcolXSLSmiwqw6l6GUFZLcnWTbGFs5aJGQeW0/a8cDP8KkPX0CkiuNMiA95231cyNDPcbm45mO5VPzFBbDcwwC0JBJVpiYrn+FAbeYjCTk8+/NqBRUDtUf1gaF2QV0Bnom5AXNPkMY1QypM=
  template:
    metadata:
      name: secrets-manager-password
      namespace: llm-gateway-internal
    type: Opaque
