---
all:
  hosts:
    llm-server-01:
      ansible_host: "{{ lookup('ansible.builtin.env', 'SERVER_PUBLIC_IP') }}"
      ansible_user: ubuntu
  children:
    llm_servers:
      hosts:
        llm-server-01:
