name: Scale Down

on:
  workflow_dispatch:
  schedule:
    # GitHub Actions schedules are UTC.
    # 20:00 CEST (summer)
    - cron: "58 17 * 4-10 1-5"
    # 20:00 CET (winter)
    - cron: "58 18 * 1-3,11-12 1-5"

permissions:
  contents: read
  id-token: write

jobs:
  destroy-vm:
    name: Destroy VM via Terraform apply
    uses: ./.github/workflows/terraform-apply.yml
    with:
      vm_enabled: "false"
    secrets: inherit

